---

version: '2'
services:
  ansiblecontroller:
    build:
      context: ./ansible
      dockerfile: Dockerfile

  ubuntu:
    build:
      context: ./ubuntu
      dockerfile: Dockerfile



  centos7:
    build:
      context: ./centos7
      dockerfile: Dockerfile

